sudo: false

language: java
jdk:
  - oraclejdk8

git:
  submodules: false
before_install: git submodule update --init --recursive

env: GRADLE_OPTS="-Xms1g -Xmx3g"
install: ./gradlew setupCIWorkspace
script: ./gradlew build

notifications:
  email: false
