sudo: false

language: java
jdk:
  - oraclejdk8

git:
  submodules: false
before_install: git submodule update --init --recursive

install: ./gradlew setupCIWorkspace
script: ./gradlew build

notifications:
  email: false
